/**
 * 真实闭环驱动脚本（host 侧，非 DSH 动态沙箱）。
 *
 * 目的：验证 OpenScout Core 在真实 GitHub 上跑通完整发布链路
 *   searchRepos → searchIssues(feasibility) → dedup → ContribOrchestrator.generate(真实 Agent)
 *   → approve → PublishEngine.publish(fork→branch→push→draft PR)
 *
 * 设计：纯 Node + tsx，require 真实编译产物与 @octokit/rest。不依赖 DSH 运行时，
 * 因此不受动态插件沙箱网络限制；token 来自 env 或 ~/.dsh/.credentials.yaml。
 *
 * 安全：仅创建 draft PR，不 publish/merge；改动为无副作用的演示文件。
 */

import { readFileSync, mkdtempSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import {
  SearchEngine,
  DedupEngine,
  ContribOrchestrator,
  PublishEngine,
  systemClock,
  type AgentPort,
  type CodeWorkResult,
  type ApprovalPort,
  type ApprovalOutcome,
} from '@openscout/core'
import { OctokitGitHubAdapter } from '@openscout/github-adapter'
import { InMemoryStorage } from '@openscout/storage-memory'

// === Token 解析（env 优先，回退 .credentials.yaml） ===
function resolveToken(): string {
  const fromEnv = process.env.GITHUB_TOKEN
  if (fromEnv) return fromEnv
  try {
    const raw = readFileSync(`${process.env.HOME ?? ''}/.dsh/.credentials.yaml`, 'utf8')
    const m = raw.match(/GITHUB_TOKEN:\s*(\S+)/)
    if (m) return m[1]
  } catch { /* ignore */ }
  throw new Error('未找到 GitHub token：请设置 GITHUB_TOKEN 环境变量，或写入 ~/.dsh/.credentials.yaml 的 GITHUB_TOKEN 键')
}

// === 真实 Agent：克隆仓库、做一次无副作用改动、返回变更文件（含路径供发布读取内容） ===
function makeRealAgent(repoFullName: string): AgentPort & { workspace: string } {
  const workspace = mkdtempSync(join(tmpdir(), 'openscout-agent-'))
  let cloned = false
  const cloneOnce = () => {
    if (cloned) return
    execFileSync('git', ['clone', `https://github.com/${repoFullName}.git`, workspace], { stdio: 'ignore' })
    cloned = true
  }
  return {
    workspace,
    async delegateCodeWork(req): Promise<CodeWorkResult> {
      cloneOnce()
      // 无副作用演示改动：在仓库根写一个 OpenScout 标记文件
      const marker = join(workspace, 'OPENSPOUT_CONTRIBUTION_PROBE.md')
      const content = `# OpenScout Contribution Probe\n\nGenerated by OpenScout real-loop at ${new Date().toISOString()}\n`
      writeFileSync(marker, content)
      return {
        success: true,
        changedFiles: [marker],
        validationResults: [{ command: 'git status', passed: true, output: '1 file changed' }],
        summary: '添加 OpenScout 探针标记文件（演示改动，无副作用）',
        diff: '',
      }
    },
  }
}

// 自动批准（演示用审批闸门；真机应由用户审批）
const autoApprove: ApprovalPort = { async requestApproval(): Promise<ApprovalOutcome> { return 'approved' } }

async function main() {
  const token = resolveToken()
  const repoArg = process.argv[2] ?? 'octocat/Hello-World'
  const [targetOwner, targetName] = repoArg.split('/')

  const storage = new InMemoryStorage()
  const github = new OctokitGitHubAdapter({ resolveGitHubToken: async () => token })
  const cred = { resolveGitHubToken: async () => token }
  void cred

  const search = new SearchEngine(github, systemClock)

  let top: { repository: { fullName: string; owner: string; name: string; githubId: number } }
  if (targetOwner && targetName) {
    // 直接指定 owner/repo：跳过仓库搜索，直接拉取仓库元数据
    console.log('[1] 使用指定仓库（跳过搜索）...')
    const repo = await github.getRepository(targetOwner, targetName)
    top = { repository: { fullName: repo.fullName, owner: repo.owner, name: repo.name, githubId: repo.githubId } }
    console.log(`    目标仓库: ${top.repository.fullName}`)
  } else {
    console.log('[1] searchRepositories ...')
    const repoRes = await search.searchRepositories({ query: targetName || 'hello world', limit: 5 })
    top = repoRes.candidates[0]
    if (!top) throw new Error('未搜到候选仓库')
    console.log(`    选定仓库: ${top.repository.fullName} (score=${top.score})`)
  }

  console.log('[2] searchIssues (feasibility) ...')
  const issueRes = await search.searchIssues({
    repository: { owner: top.repository.owner, name: top.repository.name },
    labels: ['good first issue'],
    limit: 10,
  })
  let high = issueRes.candidates.find(c => c.feasibility === 'high') ?? issueRes.candidates[0]
  if (!high) {
    // 放宽：不带标签再搜一次
    const fallback = await search.searchIssues({
      repository: { owner: top.repository.owner, name: top.repository.name },
      limit: 10,
    })
    high = fallback.candidates.find(c => c.feasibility === 'high') ?? fallback.candidates[0]
  }
  if (!high) throw new Error('未搜到可贡献 Issue')
  console.log(`    选定 Issue #${high.issue.number} (${high.feasibility}): ${high.issue.title}`)

  console.log('[3] dedup + ContribOrchestrator.generate (真实 Agent 克隆并改动) ...')
  const dedup = new DedupEngine({ storage, clock: systemClock })
  const agent = makeRealAgent(top.repository.fullName)
  const orchestrator = new ContribOrchestrator({ storage, dedup, agent, approval: autoApprove })
  const gen = await orchestrator.generate({
    repository: { owner: top.repository.owner, name: top.repository.name, githubId: top.repository.githubId },
    issue: { number: high.issue.number, githubId: high.issue.githubId, title: high.issue.title, url: high.issue.htmlUrl },
    intent: `为 ${top.repository.name} 添加 OpenScout 探针标记文件（演示贡献）`,
    workingDirectory: agent.workspace,
  })
  if (gen.kind === 'duplicate') { console.log(`    去重拦截: ${gen.reason}`); return }
  if (gen.kind === 'agent-failed') { throw new Error(`Agent 失败: ${gen.reason}`) }
  console.log(`    生成到 review 状态，workItemId=${gen.workItem.id}`)

  console.log('[4] approve (版本绑定) ...')
  const ap = await orchestrator.approve(gen.workItem.id)
  if (!ap.ok) throw new Error(`审批失败: ${ap.reason}`)
  console.log(`    approved, approvedVersion=${ap.approvedVersion}`)

  console.log('[5] PublishEngine.publish → fork/branch/push/draft PR ...')
  const publish = new PublishEngine({ storage, github, approval: autoApprove })
  // 从 Agent 工作区读出真实文件内容，构造 Commit[]
  const commits = [{
    message: 'OpenScout: 添加探针标记文件（演示贡献）',
    files: gen.bundle.changedFiles.map(p => ({ path: p.replace(agent.workspace + '/', ''), content: readFileSync(p, 'utf8') })),
  }]
  const pub = await publish.publish({ workItemId: gen.workItem.id, commits, asDraft: true })
  if (!pub.ok) throw new Error(`发布失败: ${pub.reason} (status=${pub.workItem.status})`)
  console.log(`    ✅ 已创建草稿 PR #${pub.remotePR.number}: ${pub.remotePR.url}`)
  console.log('真实闭环跑通。')
}

main().catch((e) => { console.error('真实闭环失败:', e.message); process.exit(1) })
